# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[47,)" #mandatory (24 is current forge version)

# A URL to refer people to when problems occur with this mod
issueTrackerURL="http://my.issue.tracker/" #optional

license="CC BY-NC"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
    modId="automatone" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="PlayerEngine" #mandatory
    #updateJSONURL="" #optional
    displayURL="" #optional
    #logoFile="" #optional
    #credits="" #optional
    authors="Goodbird, LadySnake" #optional
    description='''
PlayerEngine is a framework allowing you to create AI-based custom entities
    '''

[[dependencies.automatone]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.automatone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"